<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\OidcStarter.Agent.Core\OidcStarter.Agent.Core.csproj" />
    <ProjectReference Include="..\OidcStarter.Agent.Auditors.Starter\OidcStarter.Agent.Auditors.Starter.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
